# language_dict.py
# contains mapping of language names to their respective IDs (for Myanonamouse search)

language_dict = {
    "English": 1,
    "Afrikaans": 17,
    "Arabic": 32,
    "Bengali": 35,
    "Bosnian": 51,
    "Bulgarian": 18,
    "Burmese": 6,
    "Cantonese": 44,
    "Catalan": 19,
    "Chinese": 2,
    "Croatian": 49,
    "Czech": 20,
    "Danish": 21,
    "Dutch": 22,
    "Estonian": 61,
    "Farsi": 39,
    "Finnish": 23,
    "French": 36,
    "German": 37,
    "Greek": 26,
    "Greek, Ancient": 59,
    "Gujarati": 3,
    "Hebrew": 27,
    "Hindi": 8,
    "Hungarian": 28,
    "Icelandic": 63,
    "Indonesian": 53,
    "Irish": 56,
    "Italian": 43,
    "Japanese": 38,
    "Javanese": 12,
    "Kannada": 5,
    "Korean": 41,
    "Lithuanian": 50,
    "Latin": 46,
    "Latvian": 62,
    "Malay": 33,
    "Malayalam": 58,
    "Manx": 57,
    "Marathi": 9,
    "Norwegian": 48,
    "Polish": 45,
    "Portuguese": 34,
    "Brazilian Portuguese (BP)": 52,
    "Punjabi": 14,
    "Romanian": 30,
    "Russian": 16,
    "Scottish Gaelic": 24,
    "Sanskrit": 60,
    "Serbian": 31,
    "Slovenian": 54,
    "Spanish": 4,
    "Castilian Spanish": 55,
    "Swedish": 40,
    "Tagalog": 29,
    "Tamil": 11,
    "Telugu": 10,
    "Thai": 7,
    "Turkish": 42,
    "Ukrainian": 25,
    "Urdu": 15,
    "Vietnamese": 13,
    "Other": 47,
}